# Generated by Django 3.0 on 2021-09-23 06:16

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('text', models.TextField(max_length=1000, verbose_name='発明内容')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pred', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10)),
                ('proba', django_mysql.models.ListCharField(models.IntegerField(blank=True, null=True), max_length=33, size=10)),
                ('input_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
