# Generated by Django 3.0 on 2021-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfile',
            name='text',
            field=models.TextField(max_length=500, verbose_name='発明内容'),
        ),
    ]
